### PR TITLE
updated script to obtain all filenames that are previous outputfiles

### PR DESCRIPTION
**Pull request by puelloc**

### CODE REVIEW

**Review by Bruception — CHANGES_REQUESTED** [review]
This doesn't seem to be functional for `01_Parameters_SameFolder`. I'm getting `abundRaw.normalized.csv` as output. In any case, this script is contingent on the `parameter_files` script to function correctly so we should wait for that script to be ready.

**Comment by puelloc** [comment]
> This doesn't seem to be functional for `01_Parameters_SameFolder`. I'm getting `abundRaw.normalized.csv` as output. In any case, this script is contingent on the `parameter_files` script to function correctly so we should wait for that script to be ready.

image

threshold.parameters.txt is the first parameter file. 
'abundRaw.normalized.csv' is the only output file that comes before it.

Is that not supposed to be the function of the script?

**Comment by Bruception** [comment]
> > This doesn't seem to be functional for `01_Parameters_SameFolder`. I'm getting `abundRaw.normalized.csv` as output. In any case, this script is contingent on the `parameter_files` script to function correctly so we should wait for that script to be ready.
> 
> image
> 
> threshold.parameters.txt is the first parameter file.
> 'abundRaw.normalized.csv' is the only output file that comes before it.
> 
> Is that not supposed to be the function of the script?

Yeah you are right. I managed to simplify the logic a bit:
```
param_files=`parameter_files $1`

if [[ -z "$param_files" ]]
then
  echo "No parameter files in '$1'."
  exit 1
fi

valid_plugins $1 | while read line
do
	output_file=`echo $line | cut -d ' ' -f 6`
	input_file=`echo $line | cut -d ' ' -f 4`
	has_param_file=`grep $input_file $param_files`
	if [[ -z "$has_param_file" ]]
	then
		exit 1
	fi
	printf "$output_file\n"
done
```

**Comment by puelloc** [comment]
@Bruception Made the changes.

**Review by Bruception — APPROVED** [review]
LGTM

**Pull request merged**
